### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by wudizuixiaosa** [szq0214/SReT#1]
Hello, I saw that you mentioned in your paper that adding a recursive module alone is also an improvement. I don't quite understand what its specific role is. For the transformer structure, is it just feedforward not conflicting? In addition, I would like to ask if you have tried adding him to Swin, because I see from the structure that he mainly acts between steps. I am a beginner. If the question asked is very low-level, I hope you will give me some advice.

**Comment by szq0214** [comment]
Hi @wudizuixiaosa Yes, the recursive module itself can bring significant improvement. I think the role of this module is similar as the **refinement** to enhance the latent representation, and it is compatible with feedforward networks without conflicts. 

For Swin, we did not try it. I guess this module will continue increasing the performance but without other modifications, the FLOPs will also increase substantially.
