### ISSUE TITLE
参数共享

### ISSUE THREAD

**Issue by zhaoyaxinzyx** [szq0214/SReT#3]
I just started learning deep learning, so I would like to ask you how to realize parameter sharing in the iterative process of transformer. Can you cut out this small piece of code? Stupid question, thank you for your answer.。

**Comment by szq0214** [comment]
Hi @zhaoyaxinzyx, thanks for your interest in our work! You can refer to https://github.com/szq0214/SReT/blob/main/SReT.py#L163.

**Comment by zhaoyaxinzyx** [comment]
Thank you very much for your reply and help
